title: Magic Link
description: âœ‚ï¸ğŸ”— This is a URL shortener and Link clocker based on the project of https://github.com/hlaueriksson/jekyll-url-shortener
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

#repository: hlaueriksson/jekyll-url-shortener
